version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: france-services-postgres
    environment:
      POSTGRES_DB: france_services_db
      POSTGRES_USER: fs_user
      POSTGRES_PASSWORD: fs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fs_user -d france_services_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: france-services-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=france_services_db
      - DATABASE_USER=fs_user
      - DATABASE_PASSWORD=fs_password
      - DATABASE_PORT=5432
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    ports:
      - "8501:8501"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local